/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PasswordError = IDL.Variant({
  'noPassword' : IDL.Null,
  'alreadySet' : IDL.Null,
  'notFound' : IDL.Null,
  'notOwner' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : PasswordError });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const DocumentCategory = IDL.Variant({
  'finance' : IDL.Null,
  'projects' : IDL.Null,
  'education' : IDL.Null,
  'insurance' : IDL.Null,
  'achievements' : IDL.Null,
  'identity' : IDL.Null,
});
export const CategoryCount = IDL.Record({
  'count' : IDL.Nat,
  'category' : DocumentCategory,
});
export const AnalyticsOverview = IDL.Record({
  'byCategory' : IDL.Vec(CategoryCount),
  'totalDocuments' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentView = IDL.Record({
  'id' : IDL.Nat,
  'hasPassword' : IDL.Bool,
  'owner' : IDL.Principal,
  'metadata' : IDL.Vec(IDL.Text),
  'blob' : IDL.Opt(ExternalBlob),
  'name' : IDL.Opt(IDL.Text),
  'locked' : IDL.Bool,
  'fileType' : IDL.Opt(IDL.Text),
  'summary' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(DocumentCategory),
  'uploadedAt' : IDL.Int,
});
export const GraphEdge = IDL.Record({
  'source' : IDL.Text,
  'relation' : IDL.Text,
  'target' : IDL.Text,
});
export const GraphNode = IDL.Record({
  'id' : IDL.Text,
  'kind' : IDL.Text,
  'name' : IDL.Text,
});
export const KnowledgeGraph = IDL.Record({
  'edges' : IDL.Vec(GraphEdge),
  'nodes' : IDL.Vec(GraphNode),
});
export const UploadTrendPoint = IDL.Record({
  'period' : IDL.Text,
  'count' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeDocumentPassword' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getAnalyticsOverview' : IDL.Func([], [AnalyticsOverview], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Opt(DocumentView)],
      ['query'],
    ),
  'getKnowledgeGraph' : IDL.Func([], [KnowledgeGraph], ['query']),
  'getUploadTrends' : IDL.Func([], [IDL.Vec(UploadTrendPoint)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(DocumentView)], ['query']),
  'removeDocumentPassword' : IDL.Func([IDL.Nat], [Result], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchDocuments' : IDL.Func([IDL.Text], [IDL.Vec(DocumentView)], ['query']),
  'setDocumentPassword' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'verifyDocumentPassword' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PasswordError = IDL.Variant({
    'noPassword' : IDL.Null,
    'alreadySet' : IDL.Null,
    'notFound' : IDL.Null,
    'notOwner' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : PasswordError });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const DocumentCategory = IDL.Variant({
    'finance' : IDL.Null,
    'projects' : IDL.Null,
    'education' : IDL.Null,
    'insurance' : IDL.Null,
    'achievements' : IDL.Null,
    'identity' : IDL.Null,
  });
  const CategoryCount = IDL.Record({
    'count' : IDL.Nat,
    'category' : DocumentCategory,
  });
  const AnalyticsOverview = IDL.Record({
    'byCategory' : IDL.Vec(CategoryCount),
    'totalDocuments' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentView = IDL.Record({
    'id' : IDL.Nat,
    'hasPassword' : IDL.Bool,
    'owner' : IDL.Principal,
    'metadata' : IDL.Vec(IDL.Text),
    'blob' : IDL.Opt(ExternalBlob),
    'name' : IDL.Opt(IDL.Text),
    'locked' : IDL.Bool,
    'fileType' : IDL.Opt(IDL.Text),
    'summary' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(DocumentCategory),
    'uploadedAt' : IDL.Int,
  });
  const GraphEdge = IDL.Record({
    'source' : IDL.Text,
    'relation' : IDL.Text,
    'target' : IDL.Text,
  });
  const GraphNode = IDL.Record({
    'id' : IDL.Text,
    'kind' : IDL.Text,
    'name' : IDL.Text,
  });
  const KnowledgeGraph = IDL.Record({
    'edges' : IDL.Vec(GraphEdge),
    'nodes' : IDL.Vec(GraphNode),
  });
  const UploadTrendPoint = IDL.Record({
    'period' : IDL.Text,
    'count' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeDocumentPassword' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getAnalyticsOverview' : IDL.Func([], [AnalyticsOverview], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Opt(DocumentView)],
        ['query'],
      ),
    'getKnowledgeGraph' : IDL.Func([], [KnowledgeGraph], ['query']),
    'getUploadTrends' : IDL.Func([], [IDL.Vec(UploadTrendPoint)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(DocumentView)], ['query']),
    'removeDocumentPassword' : IDL.Func([IDL.Nat], [Result], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchDocuments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DocumentView)],
        ['query'],
      ),
    'setDocumentPassword' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'verifyDocumentPassword' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };