/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsOverview {
  'byCategory' : Array<CategoryCount>,
  'totalDocuments' : bigint,
}
export interface CategoryCount {
  'count' : bigint,
  'category' : DocumentCategory,
}
export interface Cell { 'value' : Value, 'name' : string }
export type DocumentCategory = { 'finance' : null } |
  { 'projects' : null } |
  { 'education' : null } |
  { 'insurance' : null } |
  { 'achievements' : null } |
  { 'identity' : null };
export interface DocumentView {
  'id' : bigint,
  'hasPassword' : boolean,
  'owner' : Principal,
  'metadata' : Array<string>,
  'blob' : [] | [ExternalBlob],
  'name' : [] | [string],
  'locked' : boolean,
  'fileType' : [] | [string],
  'summary' : [] | [string],
  'category' : [] | [DocumentCategory],
  'uploadedAt' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface GraphEdge {
  'source' : string,
  'relation' : string,
  'target' : string,
}
export interface GraphNode { 'id' : string, 'kind' : string, 'name' : string }
export interface KnowledgeGraph {
  'edges' : Array<GraphEdge>,
  'nodes' : Array<GraphNode>,
}
export type PasswordError = { 'noPassword' : null } |
  { 'alreadySet' : null } |
  { 'notFound' : null } |
  { 'notOwner' : null };
export type Result = { 'ok' : null } |
  { 'err' : PasswordError };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface UploadTrendPoint { 'period' : string, 'count' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeDocumentPassword' : ActorMethod<[bigint, string], Result>,
  'deleteDocument' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result__1>,
  'getAnalyticsOverview' : ActorMethod<[], AnalyticsOverview>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[bigint, [] | [string]], [] | [DocumentView]>,
  'getKnowledgeGraph' : ActorMethod<[], KnowledgeGraph>,
  'getUploadTrends' : ActorMethod<[], Array<UploadTrendPoint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDocuments' : ActorMethod<[], Array<DocumentView>>,
  'removeDocumentPassword' : ActorMethod<[bigint], Result>,
  'schema' : ActorMethod<[], string>,
  'searchDocuments' : ActorMethod<[string], Array<DocumentView>>,
  'setDocumentPassword' : ActorMethod<[bigint, string], Result>,
  'uploadDocument' : ActorMethod<
    [string, string, ExternalBlob, [] | [string]],
    bigint
  >,
  'verifyDocumentPassword' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];